"""initial schema

Revision ID: 9c17f02da1a1
Revises: 
Create Date: 2026-08-19 06:58:44.066032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c17f02da1a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_account_id'), 'audit_logs', ['user_account_id'], unique=False)
    op.create_table('telegram_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash_encrypted', sa.Text(), nullable=False),
    sa.Column('session_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_sessions_phone'), 'telegram_sessions', ['phone'], unique=True)
    op.create_index(op.f('ix_telegram_sessions_user_account_id'), 'telegram_sessions', ['user_account_id'], unique=False)
    op.create_table('chat_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_session_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('messages_processed', sa.BigInteger(), nullable=False),
    sa.Column('total_messages_est', sa.BigInteger(), nullable=True),
    sa.Column('files_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('files_total', sa.BigInteger(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('checkpoint_offset_id', sa.BigInteger(), nullable=True),
    sa.Column('checkpoint_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('export_dir', sa.String(length=1024), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_session_id'], ['telegram_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_exports_status'), 'chat_exports', ['status'], unique=False)
    op.create_index(op.f('ix_chat_exports_telegram_session_id'), 'chat_exports', ['telegram_session_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_export_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_export_id'], ['chat_exports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_export_id', 'message_id', 'media_type', name='uq_export_media')
    )
    op.create_index(op.f('ix_media_files_chat_export_id'), 'media_files', ['chat_export_id'], unique=False)
    op.create_index(op.f('ix_media_files_status'), 'media_files', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_export_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('forwarded_from', sa.JSON(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('media_types', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_export_id'], ['chat_exports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_export_id', 'message_id', name='uq_export_message')
    )
    op.create_index(op.f('ix_messages_chat_export_id'), 'messages', ['chat_export_id'], unique=False)
    op.create_index(op.f('ix_messages_date'), 'messages', ['date'], unique=False)
    op.create_table('migration_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_export_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('messages_converted', sa.Integer(), nullable=False),
    sa.Column('media_copied', sa.Integer(), nullable=False),
    sa.Column('output_dir', sa.String(length=1024), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_export_id'], ['chat_exports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_jobs_chat_export_id'), 'migration_jobs', ['chat_export_id'], unique=False)
    op.create_index(op.f('ix_migration_jobs_status'), 'migration_jobs', ['status'], unique=False)
    op.create_table('import_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_job_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('package_path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('users_detected', sa.JSON(), nullable=True),
    sa.Column('date_min', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_max', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['migration_job_id'], ['migration_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_packages')
    op.drop_index(op.f('ix_migration_jobs_status'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_chat_export_id'), table_name='migration_jobs')
    op.drop_table('migration_jobs')
    op.drop_index(op.f('ix_messages_date'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_export_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_media_files_status'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_chat_export_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_chat_exports_telegram_session_id'), table_name='chat_exports')
    op.drop_index(op.f('ix_chat_exports_status'), table_name='chat_exports')
    op.drop_table('chat_exports')
    op.drop_index(op.f('ix_telegram_sessions_user_account_id'), table_name='telegram_sessions')
    op.drop_index(op.f('ix_telegram_sessions_phone'), table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    op.drop_index(op.f('ix_audit_logs_user_account_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
